"""
CSC111 Final Project: Simplifying the UofT Course Selection Process

Description
===============================
This file was autogenerated by the scrapy library to set up a web-scraping framework
Note: This file is never run directly (During the running of main.py or during the web scraping process). A scrapy shell
command is used to run the entire web scraping process at once. If run directly, this file will likely error
"""
# Define your item pipelines here
#
# Don't forget to add your pipeline to the ITEM_PIPELINES setting
# See: https://docs.scrapy.org/en/latest/topics/item-pipeline.html


# useful for handling different item types with a single interface
from itemadapter import ItemAdapter

# Note: This file was automatically created by scrapy
class ScrapingPipeline:
    def process_item(self, item, spider):
        return item

if __name__ == '__main__':
    import python_ta
    import doctest
    doctest.testmod()
    python_ta.check_all(config={
        'extra-imports': [],
        'allowed-io': [''],
        'max-line-length': 120,
    })
